In [ ]:
inputs=[1.5,5.3,2.7]
weights1=[4.2,6.1,-8.3]
weights2=[2.3,5.2,3.1]
weights3=[3.3,4.1,7.3]

bias1=2
bias2=3
bias3=0.5



output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+bias3]
print(output)

[18.21999999999999, 42.379999999999995, 46.89]


In [3]:
weights=[[4.2,6.1,-8.3],
         [2.3,5.2,3.1],
         [3.3,4.1,7.3]]
biases=[2,3,0.5]
layer_outputs=[]
for neuron_weights, neuron_bias in zip(weights,biases):
    neuron_output=0
    for n_input, weight in zip(inputs,neuron_weights):
        neuron_output+=n_input*weight

    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[18.21999999999999, 42.379999999999995, 46.89]


In [6]:
import numpy as np

inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1.0],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(weights,inputs)+biases
output


array([4.8  , 1.21 , 2.385])

In [12]:
inputs =[[1.0,2.0,3.0,2.5],
         [2.0,5.0,-1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]

weights=np.array([[0.2,0.8,-0.5,1.0],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]])
output=np.dot(inputs,weights.T)+biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [13]:
weights2=[[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]

layer1_outputs=np.dot(inputs,np.array(weights).T) +biases
layer2_outputs= np.dot(layer1_outputs,np.array(weights2).T)+biases2

layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])